version: "3.7"

services:
  qg-artwork-mock-server:
    image: mockoon/cli:latest
    command: ["--data", "data", "--port", "3000"]
    ports:
      - "31000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/healthcheck || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 10s
    volumes:
      - ./mockoon-mocks.json:/data:ro
